language: node_js
node_js:
  - "node"
script:
  - sudo apt-get install npm
  - sudo npm install -g eslint
  - cd functions/
  - sudo npm install
  - cd ..
  - echo "Begin Deploy!"
  - sudo npm install -g firebase-tools
  - sudo firebase deploy --token "$FIREBAS_TOKEN"